# Generated by Django 3.2 on 2021-05-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('birth', models.DateTimeField()),
                ('gender', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
    ]
